name: 'Bazel Tests'
description: 'Runs all tests using bazel.'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ env.USE_JAVA_DISTRIBUTION }}
    - name: 'Cache bazel files'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-java-${{matrix.java}}-bazel-test-${{ hashFiles('**/WORKSPACE') }}
        restore-keys: |
          ${{ runner.os }}-java-${{matrix.java}}-bazel-test-
    - name: Bazel test
      run: bazel test --javacopt="--release 11" //... --test_output=errors
      shell: bash
