name: 'Bazel Build'
description: 'Builds artifacts and creates local snapshots maven artifacts.'

runs:
  using: "composite"
  steps:
    - name: 'Set up JDK'
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        distribution: ${{ env.USE_JAVA_DISTRIBUTION }}
        java-version: ${{ env.USE_JAVA_VERSION }}
    - name: 'Check out repository'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: 'Cache Bazel files'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-build-${{ hashFiles('**/WORKSPACE') }}
        restore-keys: |
          ${{ runner.os }}-bazel-build-
    - name: 'Bazel build'
      # Cross compile for Java 11, see http://openjdk.java.net/jeps/247
      run: bazel build --javacopt="--release 11" //...
      shell: bash
    - name: 'Install local snapshot'
      run: ./util/install-local-snapshot.sh
      shell: bash
    - name: 'Upload local snapshot for local mvn artifiact tests'
      uses: actions/upload-artifact@v4
      with:
        name: local-snapshot
        path: ~/.m2/repository/com/google/inject
